version: "3.9"

services:
  app:
    image: ghcr.io/faykgordon-sudo/opaux:latest
    environment:
      - SECRET_KEY=${SECRET_KEY:-8025047bec92077eda823e6af879b37e1db756ed9d2326ab2bdb6c1db0e945df}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ADMIN_EMAILS=${ADMIN_EMAILS:-faykgordon@gmail.com}
      - FLASK_ENV=production
      - SCHEDULER_ENABLED=0
      - MAIL_SERVER=smtp.postmarkapp.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=1
      - MAIL_DEFAULT_SENDER=noreply@opaux.com
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped

  nginx:
    image: ghcr.io/faykgordon-sudo/opaux-nginx:latest
    volumes:
      - ./data/certbot/www:/var/www/certbot:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; while :; do
        certbot renew --webroot -w /var/www/certbot --quiet;
        sleep 12h & wait $${!};
      done"
    restart: unless-stopped
